name: Release

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages to release (comma-separated, e.g. @myorg/cli,@myorg/generator)"
        required: false
        type: string
  push:
    paths:
      - "**/CHANGELOG.md"
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 9.15.4
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: pnpm i

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # Builds packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Selective Package Release
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.packages }}
        run: |
          PACKAGES=(${{ inputs.packages }})
          for PACKAGE in "${PACKAGES[@]}"; do
            pnpm changeset publish --filter=$PACKAGE
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Send a Slack notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
